export default [
    {
        id: 1,
        name: "Modem 4G LTE-A CAT6 D-Link DWR-M961 AC1200 Dual-band",
        des: "1x Gigabit WAN port – 4x Gigabit LAN ports – 1x USB 2.0 Port for Wireless file sharing – Built in SIM card slot for a mobile broadband connection – Dual Band wireless with speeds of up to 1200Mbps – LTE-A speeds of up to 300Mbps downlink and 50Mbps uplink – Dual-active firewalls (NAT/SPI)",
        price: 13900,
        best: false,
        type: "Modem",
        imgs: ["/images/item-1-2.png", "/images/item-1-3.png", "/images/item-1-1.png"],
        add: ["The D-Link DWR-M961 4G AC1200 LTE-A (CAT-6) Wireless Router allow you to access mobile broadband networks from anywhere. Once connected, you can check e-mail, surf the web, and stream media. Use your carrier’s SIM/UICC card to share your 3G/4G Internet connection & create a powerful private network for your home or small office.", "- 4x Gigabit LAN ports", "- Built in SIM card slot for a mobile broadband connection", "- Dual Band wireless with speeds of up to 1200Mbps", "- LTE-A speeds of up to 300Mbps downlink and 50Mbps uplink", "- Dual-active firewalls (NAT/SPI)"],
    },
    {
        id: 2,
        name: "Modem Router Dlink AX1800 VDSL2 / ADSL2+ DSL-X1852E Wifi 6",
        des: "MU-MIMO Modem Router Dlink AX1800 VDSL2 / ADSL2+ DSL-X1852E Wifi 6",
        price: 14900,
        best: true,
        type: "Modem",
        imgs: ["/images/item-2-1.png", "/images/item-2-2.png", "/images/item-2-3.png"],
        add: ["Wi-Fi 6 offre des vitesses plus rapides, une plus grande capacité et moins de congestion du réseau Vitesses jusqu'à AX1800 (1 200 Mbps sur 5 GHz et 574 Mbps sur 2,4 GHz)", "Modem ADSL2+/VDSL2 intégré pour vous connecter à votre connexion Internet haut débit haut débit Quatre ports LAN Gigabit pour connecter des appareils filaires pour des activités en ligne à haut débit", "Les technologies MU-MIMO communique plus de données à plus d'appareils tout en réduisant simultanément le décalage", "Port USB 3.0 super rapide pour partager des médias à partir d'un périphérique de stockage ou connecter un adaptateur USB 4G LTE (DWM-222)"]
    },
    {
        id: 3,
        name: "Routeur EAGLE PRO AI AX1500 R15 Wifi 6",
        des: "Wi-Fi 6 AX1500 bibande ,2,4 GHz (jusqu’à 300 Mbit/s), 5 GHz (jusqu’à 1201 Mbit/s), WiFi Mesh, MU-MIMO et OFDMA",
        price: 11800,
        best: false,
        type: "Routeurs Wifi",
        imgs: ["/images/item-3-1.png", "/images/item-3-2.png"],
        add: ["Wi-Fi 6 AX1500 bibande 2,4 GHz (jusqu’à 300 Mbit/s), 5 GHz (jusqu’à 1201 Mbit/s)", "Assistant AI", "Optimisations Mesh, du Wi-Fi et du trafic par l’IA1 Efficacité MU-MIMO et OFDMA", "Commande vocale avec Google/Alexa", "Sécurité sans fil WPA3", "Configuration et gestion faciles"],
    },
    {
        id: 4,
        name: "Routeur Dlink MU-MIMO GIGABIT AC1200 DIR-825M",
        des: "Routeur Dlink MU-MIMO GIGABIT AC1200 DIR-825M WIFI 5 (Livraison gratuite)",
        price: 6500,
        best: true,
        type: "Routeurs Wifi",
        imgs: ["/images/item-4-1.png", "/images/item-4-2.png", "/images/item-4-3.png"],
        add: ["- Transfert haut débit jusqu'à 300 Mbps (2,4 GHz) + 867 Mbps (5,0 GHz)", "- 4 ports Gigabit 10/100/1000 offrent des performances ultra-rapides jusqu'à 10 fois plus rapides que le Fast Ethernet traditionnel", "- La double bande simultanée rend vos flux 4K et vos jeux en ligne plus fluides avec moins d'interférences", "- Un système QoS optimisé offre une expérience de jeu en ligne améliorée sans LAG", "- USB 2.0 à partager sur votre réseau local", "- Plusieurs modes de fonctionnement Routeur/Point d'accès/Répéteur/Répéteur Mesh*/ Répéteur WISP /Client Wi-Fi"],
    },
    {
        id: 5,
        name: 'PC PORT OCCASION HP 640 G2 I5 6eme/ 8 / 256 / 14" NO AC',
        des: "HP EliteBook 640 G10 i5 1345U 16G 512 SSD 14 Full HD Tactile Neuf",
        price: 39900,
        best: true,
        type: "Laptop",
        imgs: ["/images/item-5-1.png", "/images/item-5-2.png", "/images/item-5-3.jpg"],
        add: ["Processeur : Intel Core i5 6eme", "RAM : 8GB DDR4", "Stockage : 256GB SSD", "Processeur graphique : Intel FHD Graphics", `Taille d'ecran : 14" FHD`, "Système d'exploitation : Windows 10 PRO"],
    }
    ,
    {
        id: 6,
        name: 'LENOVO Portable 2-en-1 300e',
        des: "Enseignants qui pensez qu’une salle de classe ressemble parfois à un champ de bataille, reprenez espoir : cet outil présente une robustesse de niveau militaire ! Grande solidité grâce aux protections en caoutchouc, ports et charnières renforcés, clavier scellé, touches mécaniques : le 2-en-1 300e (2e gén.) peut résister à toutes les formes de chocs et de mauvais traitements. Il est même résistant aux chutes de jusqu’à 75 cm de hauteur, c’est-à-dire à peu près la hauteur d’un bureau d’écolier !",
        price: 33900,
        best: true,
        type: "Laptop",
        imgs: ["/images/item-6-1.png", "/images/item-6-2.png", "/images/item-6-3.png"],
        add: ["Batterie : Jusqu’à 10 heures d’autonomie*, 42 Wh", "Caméra: En option : caméra 5 Mpx à l’arrière", "Dimensions (L x P x H) : 290 x 204 x 20,85 mm"],
    }
    ,
    {
        id: 7,
        name: 'DELL G7 I7 8750H 4.1GHZ 17.3″ 1MS 144HZ IPS WIN10 RTX2060 6GO DELL G7',
        des: "Gagnez en confort et en performance de jeu avec le PC portable Dell G7 17-7790 ! Malgré son design mince et élégant, cet ordinateur est une véritable machine de guerre ! Avec ses composants ultra-performants, son écran IPS 144 Hz, son clavier rétroclairé et son système audio performant, il offre un haut niveau de confort de jeu.",
        price: 159900,
        best: false,
        type: "Laptop",
        imgs: ["/images/item-7-1.png", "/images/item-7-2.png", "/images/item-7-3.png", "/images/item-7-4.png"],
        add: ["Processeur Intel Core i7-8750H (Hexa-Core 2.2 GHz / 4.1 GHz Turbo – Cache 9 Mo)", "16 Go de mémoire vive DDR4 2666 MHz (1x 16 Go – maximum 16 Go)", "Ecran de 17.3″ avec résolution Full HD (1920 x 1080 pixels) et fréquence de 144 Hz", "Dalle IPS : couleurs lumineuses et angles de vision larges", "Carte graphique NVIDIA GeForce RTX 2060 (Max-Q) avec 6 Go de mémoire dédiée GDDR6"],
    }
    ,
    {
        id: 8,
        name: 'CANON G2410 IMPRIMANTE MULTIFONCTION',
        des: "Bénéficiez d’une impression productive extrêmement rentable avec de hauts rendements*, jusqu’à 6000 pages avec une bouteille d’encre noire et 7000 pages avec un kit de bouteilles d’encre couleur.",
        price: 36900,
        best: true,
        type: "Imprimantes",
        imgs: ["/images/item-8-1.png", "/images/item-8-2.png"],
        add: ["Imprimez facilement vos photos de manière innovante et créative grâce au logiciel photo My Image Garden.", "Profitez d’une connexion USB rapide et facile à votre PC et d’une grande facilité utilisation avec l’écran LCD 1,2"],
    }
    ,
    {
        id: 9,
        name: 'IMPRIMANTE TICKET DE CAISSE/CODE BARRE MOBILE BT-SPRT AVEC BATTERIE',
        des: "SP-L31",
        price: 34000,
        best: false,
        type: "Imprimantes",
        imgs: ["/images/item-9-1.png", "/images/item-9-2.png", "/images/item-9-3.png"],
        add: ["USB 2.0, bluetooth", "8 pts/mm, 576 pts/mm"],
    }
]